### PR TITLE
Update Code39.php

### PR DESCRIPTION
**Pull request by KevinHansen23**
Fix for: Array and string offset access syntax with curly braces is no longer supported

### CODE REVIEW

**Comment by erkens** [comment]
When I remember correct that (stupid) syntax was deprecated with PHP 7.4. Can you add the php 7.4 requirement to compose.json? That way if someone is using it with an ancient PHP version it will not break.

**Comment by KevinHansen23** [comment]
I can do that but I don't think it's necessary. The square bracket syntax has been valid since at least June 2008: https://wiki.php.net/rfc/deprecate_curly_braces_array_access#wasn_t_the_curly_brace_syntax_deprecated_once_before

Do you still want me to add the requirement?

Edit: It has been there a lot longer: https://externals.io/message/38153

**Comment by erkens** [comment]
Also true, if someone isn't using a "recent" version of PHP they most likely are not using this, let alone run "composer update". If they are, the can pin the version....

~~I will merge it~~, thanks :) (and you can see I'm not using Code39 myself :D )

**Comment by KevinHansen23** [comment]
You're welcome. 

We've only implemented Code39, so together we are covering the complete Codebase :-)

**Comment by erkens** [comment]
But after a quick look it was deprecated with 7.4 although it should have been depreacted with 6.0 which was never released) so this code will only break with 8.x and 8.0 is still "supported".

**Comment by KevinHansen23** [comment]
Yeah makes sense. We are running 8.1.

**Comment by erkens** [comment]
if you can add `"php": ">8.0",` to the require section of composer.json I will merge it directly :)

**Comment by KevinHansen23** [comment]
Are you sure? The fix runs perfectly fine on PHP 7 and almost certainly even on all Versions of PHP 5.

**Comment by erkens** [comment]
Good point, I was focussed on the "deprecation" and not that this ugly syntax wan't in use for decades...

**Pull request merged**
